In [2]:
import numpy as np

np.set_printoptions(suppress=True) # Valores cercanos a 0 seran mostrados como 0

In [3]:
A = np.array([[2, 3], [5, 7], [11, 13]])
A

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [5]:
U, D, V = np.linalg.svd(A)
print('U\n', U)
print('D\n', D)
print('V\n', V)

U
 [[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
 [19.40321383  0.71783924]
V
 [[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [6]:
D_pseudo = np.zeros((A.shape[0], A.shape[1])).T 
D_pseudo

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
print('D_pseudo')
D_pseudo[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pseudo)

D_pseudo
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [10]:
A_pseudo = V.T.dot(D_pseudo).dot(U.T)
A_pseudo

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [11]:
A_pseudo_calc = np.linalg.pinv(A) # Pseudoinversa de Moore Penrose de matriz A
A_pseudo_calc

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [14]:
A_pseudo_calc @ A # Muy cercano a la matriz identidad

array([[ 1., -0.],
       [ 0.,  1.]])

In [15]:
np.set_printoptions(suppress=False)
A_pseudo_calc @ A

array([[ 1.00000000e+00, -8.88178420e-16],
       [ 2.66453526e-15,  1.00000000e+00]])

In [16]:
A_pseudo_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)

In [18]:
# Son la misma matriz
print(A_pseudo_calc)
print(A_pseudo_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
