In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[3,2], [4, 1]])
A

array([[3, 2],
       [4, 1]])

In [3]:
np.linalg.eig(A) # Eigenvalues and eigenvectors (autovalores y autovectores)

(array([ 5., -1.]), array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))

In [4]:
autovalores, autovectores = np.linalg.eig(A)

In [5]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [6]:
np.linalg.eig(A)[1][:,0] # Autovector 1

array([0.70710678, 0.70710678])