In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

**Metodo SVD (Descomposición por valores singulares)**

In [4]:
U, D, V = np.linalg.svd(A)

In [5]:
print(U)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]


In [6]:
print(np.diag(D))

[[9.508032   0.        ]
 [0.         0.77286964]]


In [7]:
print(V)

[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
