In [1]:
import numpy as np

In [2]:
A = np.array([[3, 2], [4, 1]])
A

array([[3, 2],
       [4, 1]])

In [3]:
autovalores, autovectores = np.linalg.eig(A)

In [5]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


**Descomposición 1**: A =   (v = matriz de autovectores)(lamda = matriz de autovalores en la diagonal)(v^-1)

In [6]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [7]:
A_calc # Misma matriz que A, pues resulto de la descomposicion de la matriz original

array([[3., 2.],
       [4., 1.]])

**Descomposición 2**: Para una matriz real (de número reales) y simetrica (A.T == A).

A = (v = matriz de autovectores)(lamda = matriz con autovalores en la diagonal)(v.T)

In [9]:
A = np.array([[3, 2], [2, 3]])
A

array([[3, 2],
       [2, 3]])

In [10]:
A == A.T # Es simetrica

array([[ True,  True],
       [ True,  True]])

In [11]:
autovalores, autovectores = np.linalg.eig(A)

print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [12]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)

In [13]:
A_calc # Misma matriz que A, pues resulto de la descomposicion de la matriz original

array([[3., 2.],
       [2., 3.]])